// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.26;

import {Test} from "forge-std/Test.sol";
import {OracleMath} from "../../src/libraries/OracleMath.sol";
import {MarketHours} from "../../src/MarketHours.sol";
import {IMarketHours} from "../../src/interfaces/IMarketHours.sol";
import {StockWrapper} from "../../src/StockWrapper.sol";
import {LendoraOracle} from "../../src/oracles/LendoraOracle.sol";
import {LendoraOracleBase} from "../../src/oracles/LendoraOracleBase.sol";
import {ILendoraOracle} from "../../src/interfaces/ILendoraOracle.sol";
import {MockStockToken} from "../mocks/MockStockToken.sol";
import {MockChainlinkAggregator} from "../mocks/MockChainlinkAggregator.sol";
import {MockCollateralToken} from "../mocks/MockCollateralToken.sol";

/// @notice Exposes the internal library so vectors are checked against the exact bytecode path the oracle uses.
contract OracleMathHarness {
    function fullBuffer(uint256 z, uint256 s, uint256 lo, uint256 hi, uint256 len) external pure returns (uint256) {
        return OracleMath.fullBuffer(z, s, lo, hi, len);
    }

    function stockLoanPrice(uint256 v, uint256 u, uint256 p, uint256 b, uint256 e) external pure returns (uint256) {
        return OracleMath.stockLoanPrice(v, u, p, b, e);
    }

    function receiptPrice(uint256 a, uint256 p, uint256 u, uint256 b, uint256 e) external pure returns (uint256) {
        return OracleMath.receiptPrice(a, p, u, b, e);
    }

    function healthFactor(uint256 c, uint256 p, uint256 l, uint256 b) external pure returns (uint256) {
        return OracleMath.healthFactor(c, p, l, b);
    }
}

/// @notice OR-R1, OR-R20, OR-R22: Solidity equals the SDK exactly on the shared vectors in `test/vectors/`
/// (generated by `packages/sdk/scripts/genVectors.ts`; ≥ 10k buffer and price cases incl. DST weeks and holidays).
contract OracleVectorsTest is Test {
    // Structs mirror the JSON objects; forge decodes keys in alphabetical order.
    struct BufferCase {
        uint256 expected;
        uint256 t;
        uint256 u;
    }

    struct PriceCase {
        uint256 b;
        uint256 expected;
        uint256 p;
        uint256 u;
        uint256 vpt;
    }

    struct ReceiptCase {
        uint256 a;
        uint256 b;
        uint256 expected;
        uint256 p;
        uint256 u;
    }

    struct FullCase {
        uint256 bMax;
        uint256 bMin;
        uint256 expected;
        uint256 len;
        uint256 sigma;
        uint256 z;
    }

    struct HealthCase {
        uint256 borrowed;
        uint256 collateral;
        uint256 expected;
        uint256 lltv;
        uint256 price;
    }

    OracleMathHarness internal h = new OracleMathHarness();

    function _read(string memory name) internal view returns (string memory) {
        return vm.readFile(string.concat("test/vectors/", name));
    }

    function test_OR_R1_priceVectorsMatchSdk() public view {
        string memory json = _read("price.json");
        uint256 e = vm.parseJsonUint(json, ".scaleExp");
        PriceCase[] memory cases = abi.decode(vm.parseJson(json, ".cases"), (PriceCase[]));
        assertGe(cases.length, 10_000);
        for (uint256 i; i < cases.length; i++) {
            PriceCase memory c = cases[i];
            assertEq(h.stockLoanPrice(c.vpt, c.u, c.p, c.b, e), c.expected, vm.toString(i));
        }
    }

    function test_OR_R1_receiptPriceVectorsMatchSdk() public view {
        string memory json = _read("receipt.json");
        uint256 e = vm.parseJsonUint(json, ".scaleExp");
        ReceiptCase[] memory cases = abi.decode(vm.parseJson(json, ".cases"), (ReceiptCase[]));
        for (uint256 i; i < cases.length; i++) {
            ReceiptCase memory c = cases[i];
            assertEq(h.receiptPrice(c.a, c.p, c.u, c.b, e), c.expected, vm.toString(i));
        }
    }

    function test_OR_R20_fullBufferVectorsMatchSdk() public view {
        FullCase[] memory cases = abi.decode(vm.parseJson(_read("fullbuffer.json"), ".cases"), (FullCase[]));
        for (uint256 i; i < cases.length; i++) {
            FullCase memory c = cases[i];
            assertEq(h.fullBuffer(c.z, c.sigma, c.bMin, c.bMax, c.len), c.expected, vm.toString(i));
        }
    }

    function test_OR_R22_healthFactorVectorsMatchSdk() public view {
        HealthCase[] memory cases = abi.decode(vm.parseJson(_read("health.json"), ".cases"), (HealthCase[]));
        for (uint256 i; i < cases.length; i++) {
            HealthCase memory c = cases[i];
            assertEq(h.healthFactor(c.collateral, c.price, c.lltv, c.borrowed), c.expected, vm.toString(i));
        }
    }

    /// @notice 12k (t, lastGoodUpdatedAt) cases through the deployed oracle's `bufferAt`, over the generated
    /// 2026-06 → 2027-12 feed calendar (DST weeks, Good Friday, Thanksgiving + early close, 3-day weekends, holiday
    /// freezes) and synthetic event windows, including before the first and after the last session.
    function test_OR_R20_R23_bufferVectorsMatchSdk() public {
        string memory json = _read("buffer.json");
        MockStockToken stock = new MockStockToken("NVDA", "NVDA", 18);
        StockWrapper w = new StockWrapper(address(stock), "NVDA", address(0));
        MockChainlinkAggregator feed = new MockChainlinkAggregator(8, "NVDA");
        MockChainlinkAggregator usdg = new MockChainlinkAggregator(8, "USDG");
        feed.setAnswer(100e8);
        usdg.setAnswer(1e8);
        MarketHours mh = new MarketHours(address(this));

        _loadCalendar(json, mh, address(stock));

        ILendoraOracle.Params memory p = ILendoraOracle.Params({
            zWad: uint64(vm.parseJsonUint(json, ".params.z")),
            sigmaWad: uint64(vm.parseJsonUint(json, ".params.sigma")),
            bMinWad: uint64(vm.parseJsonUint(json, ".params.bMin")),
            bMaxWad: uint64(vm.parseJsonUint(json, ".params.bMax")),
            rampIn: uint32(vm.parseJsonUint(json, ".params.rampIn")),
            stockHeartbeat: 86_400,
            usdgHeartbeat: 86_400,
            staleGrace: 600,
            sequencerGrace: 3600,
            bandLowWad: 0.5e18,
            bandHighWad: 2e18,
            maxQuietMultiplierStepWad: 0.05e18
        });
        LendoraOracle oracle = new LendoraOracle(
            LendoraOracleBase.Deployment(
                address(feed),
                address(usdg),
                address(stock),
                address(w),
                address(mh),
                address(this),
                address(0),
                address(0),
                address(0),
                address(0)
            ),
            p,
            address(new MockCollateralToken())
        );

        BufferCase[] memory cases = abi.decode(vm.parseJson(json, ".cases"), (BufferCase[]));
        assertGe(cases.length, 10_000);
        uint256 nonZero;
        for (uint256 i; i < cases.length; i++) {
            BufferCase memory c = cases[i];
            uint256 got = oracle.bufferAt(c.t, c.u);
            if (got != c.expected) {
                emit log_named_uint("case", i);
                emit log_named_uint("t", c.t);
                emit log_named_uint("u", c.u);
                assertEq(got, c.expected);
            }
            if (got != 0) nonZero++;
        }
        assertGt(nonZero, cases.length / 2, "vectors exercise the buffer");
    }

    /// @dev Flat arrays (forge's object-to-struct decoding can reorder same-named fields).
    function _loadCalendar(string memory json, MarketHours mh, address stock) internal {
        uint256[] memory opens = vm.parseJsonUintArray(json, ".sessionOpens");
        uint256[] memory closes = vm.parseJsonUintArray(json, ".sessionCloses");
        IMarketHours.Session[] memory s = new IMarketHours.Session[](opens.length);
        for (uint256 i; i < opens.length; i++) {
            s[i] = IMarketHours.Session(uint64(opens[i]), uint64(closes[i]));
        }
        mh.replaceSessionsFrom(0, s);
        uint256[] memory st = vm.parseJsonUintArray(json, ".eventStarts");
        uint256[] memory en = vm.parseJsonUintArray(json, ".eventEnds");
        uint256[] memory bu = vm.parseJsonUintArray(json, ".eventBuffers");
        IMarketHours.EventWindow[] memory ev = new IMarketHours.EventWindow[](st.length);
        for (uint256 i; i < st.length; i++) {
            ev[i] = IMarketHours.EventWindow(uint64(st[i]), uint64(en[i]), uint64(bu[i]));
        }
        mh.replaceEventsFrom(stock, 0, ev);
    }
}
