// Copies ABIs of Stockline contracts (contracts/src) from Foundry output into packages/sdk/abis.
// Run `forge build` in contracts/ first.
import {readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync} from "node:fs";
import {join, basename, dirname} from "node:path";
import {fileURLToPath} from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const contracts = join(here, "../../../contracts");
const outDir = join(here, "../abis");
mkdirSync(outDir, {recursive: true});

const walk = (dir) =>
  readdirSync(dir, {withFileTypes: true}).flatMap((e) =>
    e.isDirectory() ? walk(join(dir, e.name)) : e.name.endsWith(".sol") ? [join(dir, e.name)] : [],
  );

let n = 0;
for (const src of walk(join(contracts, "src"))) {
  if (src.includes(`${"/"}mocks${"/"}`)) continue;
  const file = basename(src);
  const artifactDir = join(contracts, "out", file);
  if (!existsSync(artifactDir)) continue;
  for (const art of readdirSync(artifactDir)) {
    const {abi} = JSON.parse(readFileSync(join(artifactDir, art), "utf8"));
    writeFileSync(join(outDir, art), JSON.stringify(abi, null, 2) + "\n");
    n++;
  }
}
console.log(`exported ${n} ABIs to ${outDir}`);

// Typed ABI constants for viem (keepers, indexer, app): packages/sdk/src/abis.ts. Explicit list so the file only
// changes when an interface we depend on changes.
const typed = [
  ["stockWrapperAbi", "StockWrapper.sol/StockWrapper.json"],
  ["collateralTokenAbi", "CollateralToken.sol/CollateralToken.json"],
  ["marketHoursAbi", "MarketHours.sol/MarketHours.json"],
  ["stocklineOracleAbi", "StocklineOracle.sol/StocklineOracle.json"],
  ["stocklineRouterAbi", "StocklineRouter.sol/StocklineRouter.json"],
  ["stocklineLiquidatorAbi", "StocklineLiquidator.sol/StocklineLiquidator.json"],
  ["vaultV2Abi", "IMorphoVaultV2.sol/IVaultV2Min.json"],
  ["marketAdapterAbi", "IMorphoVaultV2.sol/IMorphoMarketV1AdapterV2Min.json"],
  ["morphoAbi", "IMorpho.sol/IMorpho.0.8.19.default.json"],
  ["aggregatorV3Abi", "AggregatorV3Interface.sol/AggregatorV3Interface.json"],
  ["mockAggregatorAbi", "MockChainlinkAggregator.sol/MockChainlinkAggregator.json"],
  ["mockUniswapV3PoolAbi", "MockUniswapV3Pool.sol/MockUniswapV3Pool.json"],
  ["mockStockTokenAbi", "MockStockToken.sol/MockStockToken.json"],
  ["erc20Abi", "IERC20.sol/IERC20.json"],
  // Phase 2: full Vault V2 (events for the indexer), the IRM (rate views), Stock Token multiplier events, and the
  // anvil mocks the chain driver moves (swap aggregator rates, USDG mint, issuer registry).
  ["shortInterestLensAbi", "ShortInterestLens.sol/ShortInterestLens.json"],
  ["vaultV2FullAbi", "VaultV2.sol/VaultV2.json"],
  ["adaptiveCurveIrmAbi", "AdaptiveCurveIrm.sol/AdaptiveCurveIrm.json"],
  ["scaledUiAmountAbi", "IScaledUIAmount.sol/IScaledUIAmount.json"],
  ["mockSwapAggregatorAbi", "MockSwapAggregator.sol/MockSwapAggregator.json"],
  ["mockUsdgAbi", "MockUSDG.sol/MockUSDG.json"],
  ["mockRegistryAbi", "MockAccessControlsRegistry.sol/MockAccessControlsRegistry.json"],
  // Phase 3: fees (FE-R1…R5).
  ["feeSplitterAbi", "FeeSplitter.sol/FeeSplitter.json"],
];
let ts = "// Generated by scripts/export-abis.mjs from contracts/out. Do not edit.\n\n";
let m = 0;
for (const [name, rel] of typed) {
  const p = join(contracts, "out", rel);
  if (!existsSync(p)) {
    console.warn(`skip ${name}: ${rel} not built`);
    continue;
  }
  const {abi} = JSON.parse(readFileSync(p, "utf8"));
  ts += `export const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
  m++;
}
writeFileSync(join(here, "../src/abis.ts"), ts);
console.log(`wrote ${m} typed ABIs to src/abis.ts`);
void basename;
void dirname;
