/**
 * Generates the MarketHours calendar (OR-R11): Chainlink 24/5 feed sessions from the NYSE holiday calendar, and
 * earnings event windows from data/events.json. Writes data/calendar.json, which the deploy scripts and the
 * test-vector generator read.
 *
 *   pnpm --filter @stockline/sdk gen:sessions [from=2026-06-22] [to=2027-12-31]
 */
import {readFileSync, writeFileSync} from "node:fs";
import {dirname, join} from "node:path";
import {fileURLToPath} from "node:url";
import {eventWindowsByTicker, type EventsFile} from "../src/calendar/events.js";
import {generateSessions} from "../src/calendar/sessions.js";
import {parseYmd} from "../src/calendar/time.js";

const here = dirname(fileURLToPath(import.meta.url));
const from = process.argv[2] ?? "2026-06-22";
const to = process.argv[3] ?? "2027-12-31";

const sessions = generateSessions(parseYmd(from), parseYmd(to));
const events: EventsFile = JSON.parse(readFileSync(join(here, "../data/events.json"), "utf8"));
const windows = eventWindowsByTicker(events);

const iso = (t: number) => new Date(t * 1000).toISOString().replace(".000Z", "Z");
const out = {
  $comment:
    "Generated by packages/sdk/scripts/genSessions.ts. Do not edit. Feed sessions (UTC) per D2: trading day D is live from D-1 20:00 ET to D 20:00 ET (17:00 on early closes, A9); weekends and NYSE holidays frozen. Event windows from data/events.json (D5).",
  from,
  to,
  // Flat arrays for forge (vm.parseJsonUintArray); the objects below are for humans.
  sessionOpens: sessions.map((s) => s.openTs),
  sessionCloses: sessions.map((s) => s.closeTs),
  eventArrays: Object.fromEntries(
    Object.entries(windows).map(([t, list]) => [
      t,
      {starts: list.map((w) => w.startTs), ends: list.map((w) => w.endTs), buffers: list.map((w) => w.bufferWad.toString())},
    ]),
  ),
  sessions: sessions.map((s) => ({openTs: s.openTs, closeTs: s.closeTs, openUtc: iso(s.openTs), closeUtc: iso(s.closeTs)})),
  events: Object.fromEntries(
    Object.entries(windows).map(([t, list]) => [
      t,
      list.map((w) => ({startTs: w.startTs, endTs: w.endTs, bufferWad: w.bufferWad.toString(), endUtc: iso(w.endTs)})),
    ]),
  ),
};
writeFileSync(join(here, "../data/calendar.json"), JSON.stringify(out, null, 2) + "\n");
console.log(`wrote ${sessions.length} sessions (${from}..${to}) and ${events.events.length} events to data/calendar.json`);
