/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All stocks, current snapshot (07 §Definitions) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Snapshots */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MarketsResponse"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited (SI-R10) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Indexer not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/markets/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One stock: snapshot + params (LLTV, caps, U_MAX, buffer now, next session) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    symbol: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Snapshot and parameters */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MarketDetailResponse"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited (SI-R10) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Indexer not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/markets/{symbol}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Time series of the snapshot fields (1m / 1h / 1d buckets); `format=csv` for CSV (SI-R12) */
        get: {
            parameters: {
                query?: {
                    interval?: "1m" | "1h" | "1d";
                    /** @description Inclusive; default: 7 days before `to` */
                    from?: string;
                    /** @description Exclusive; default: now */
                    to?: string;
                    /** @description SI-R12 */
                    format?: "json" | "csv";
                    limit?: number;
                };
                header?: never;
                path: {
                    symbol: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description History */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HistoryResponse"];
                        "text/csv": string;
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited (SI-R10) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Indexer not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/markets/{symbol}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event feed, newest first, paginated with `cursor` */
        get: {
            parameters: {
                query?: {
                    type?: "borrow" | "repay" | "liquidate" | "lend" | "withdrawLend" | "all";
                    /** @description `nextCursor` of the previous page */
                    cursor?: string;
                    /** @description Only events of this wallet (public onchain data) */
                    account?: string;
                    limit?: number;
                };
                header?: never;
                path: {
                    symbol: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventsResponse"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited (SI-R10) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Indexer not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/positions/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Positions of a wallet in Lendora markets (public onchain data) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    address: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Positions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PositionsResponse"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited (SI-R10) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Indexer not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oracle freshness, guard state and indexer lag per market */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusResponse"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited (SI-R10) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Indexer not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/protocol/revenue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Performance fees per stock per day, in Stock Token units and USD; distributions and conversions (FE-R5) */
        get: {
            parameters: {
                query?: {
                    /** @description First UTC day (default: 90 days ago) */
                    from?: string;
                    /** @description Last UTC day, inclusive (default: today) */
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revenue */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RevenueResponse"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited (SI-R10) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Indexer not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vault/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** USDG Earn: share price, net APY (7/30/90d, historical, variable), yield split, sleeves, delta, margin, venue, queue (DN-R11) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Overview */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VaultOverviewResponse"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited (SI-R10) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Indexer not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vault/account/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** USDG Earn position of an address: shares, value at the current share price, net deposits, withdrawal requests */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    address: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Account */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VaultAccountResponse"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited (SI-R10) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Indexer not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/receipt-markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** G5 receipt markets (rSTOCK collateral, USDG loans): totals, utilization, LLTV (A3) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Receipt markets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReceiptMarketsResponse"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited (SI-R10) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Indexer not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data terms of use (SI-R14) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Terms */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TermsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/nonce": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One-time nonce for a Sign-In with Ethereum message */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Nonce */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NonceResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Keys of the wallet that owns the `X-API-Key` */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Keys */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KeysResponse"];
                    };
                };
                /** @description No key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /** Create an API key by signing a SIWE message (the key is shown once) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        message: string;
                        signature: string;
                        label?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateKeyResponse"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Bad signature */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Too many keys */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited (SI-R10) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Indexer not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke one of the wallet's keys */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            revoked: boolean;
                        };
                    };
                };
                /** @description No key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MarketsResponse: {
            /**
             * @description Block the data is as of (SI-R13)
             * @example 1000000000000000000
             */
            asOfBlock: string;
            /**
             * @description ISO 8601 UTC
             * @example 2026-10-01T16:00:00.000Z
             */
            asOfTime: string;
            /** @description asOfBlock ≤ the chain's finalized block (SI-R3) */
            confirmed: boolean;
            /** @description asOfBlock ≤ the chain's safe block */
            safe: boolean;
            scope: string;
            data: components["schemas"]["Market"][];
        };
        Market: {
            symbol: string;
            /** @example 0x0000000000000000000000000000000000000000 */
            stockToken: string;
            marketId: string;
            /**
             * @description Integer as a decimal string (raw onchain units)
             * @example 1000000000000000000
             */
            blockNumber: string;
            /**
             * @description ISO 8601 UTC
             * @example 2026-10-01T16:00:00.000Z
             */
            time: string;
            /**
             * @description Market supply + rSTOCK idle, shares of stock after the multiplier
             * @example 1234.56
             */
            supplied: string;
            /**
             * @description Short interest: market borrow, shares of stock after the multiplier
             * @example 1234.56
             */
            borrowed: string;
            /**
             * @description totalBorrowAssets × P_wrapped (feed, no buffer)
             * @example 1234.56
             */
            borrowedUsd: string;
            /**
             * @description Stock-loan market utilization (0–1)
             * @example 1234.56
             */
            utilization: string;
            /**
             * @description borrowed / supplied incl. the idle reserve (0–1)
             * @example 1234.56
             */
            utilizationVault: string;
            /**
             * @description Decimal string
             * @example 1234.56
             */
            borrowApr: string;
            borrowApy: number;
            /** @description Variable lender APY through rSTOCK, net of the vault performance fee */
            supplyApy: number;
            /** @enum {string} */
            rateKind: "variable";
            /**
             * @description borrowed / Stock Token totalSupply (0–1)
             * @example 1234.56
             */
            siPctFloat: string;
            daysToCover: number | null;
            borrowers: number;
            /**
             * @description Decimal string
             * @example 1234.56
             */
            newShorts24h: string;
            /**
             * @description Decimal string
             * @example 1234.56
             */
            covered24h: string;
            /** @enum {string} */
            marketStatus: "open" | "closed" | "ramping" | "guard_tripped";
            price: {
                /**
                 * @description Decimal string
                 * @example 1234.56
                 */
                usdPerShare: string;
                /**
                 * @description Decimal string
                 * @example 1234.56
                 */
                usdPerToken: string;
                /**
                 * @description ISO 8601 UTC
                 * @example 2026-10-01T16:00:00.000Z
                 */
                feedUpdatedAt: string;
                /**
                 * @description Decimal string
                 * @example 1234.56
                 */
                multiplier: string;
            };
            /**
             * @description Oracle buffer in force (0–0.2)
             * @example 1234.56
             */
            buffer: string;
            guard: {
                tripped: boolean;
                reasons: string[];
            };
            raw: {
                /**
                 * @description Integer as a decimal string (raw onchain units)
                 * @example 1000000000000000000
                 */
                suppliedShares: string;
                /**
                 * @description Integer as a decimal string (raw onchain units)
                 * @example 1000000000000000000
                 */
                borrowedShares: string;
                /**
                 * @description Integer as a decimal string (raw onchain units)
                 * @example 1000000000000000000
                 */
                utilizationWad: string;
                /**
                 * @description Integer as a decimal string (raw onchain units)
                 * @example 1000000000000000000
                 */
                borrowRatePerSecWad: string;
                /**
                 * @description Integer as a decimal string (raw onchain units)
                 * @example 1000000000000000000
                 */
                bufferWad: string;
                marketOpen: boolean;
                /**
                 * @description Integer as a decimal string (raw onchain units)
                 * @example 1000000000000000000
                 */
                guardReasons: string;
                /**
                 * @description Integer as a decimal string (raw onchain units)
                 * @example 1000000000000000000
                 */
                totalSupplyAssets: string;
                /**
                 * @description Integer as a decimal string (raw onchain units)
                 * @example 1000000000000000000
                 */
                totalBorrowAssets: string;
                /**
                 * @description Integer as a decimal string (raw onchain units)
                 * @example 1000000000000000000
                 */
                vaultIdle: string;
                /**
                 * @description Integer as a decimal string (raw onchain units)
                 * @example 1000000000000000000
                 */
                stockAnswer: string;
                /**
                 * @description Integer as a decimal string (raw onchain units)
                 * @example 1000000000000000000
                 */
                usdgAnswer: string;
                /**
                 * @description Integer as a decimal string (raw onchain units)
                 * @example 1000000000000000000
                 */
                multiplier: string;
            };
        };
        Error: {
            error: string;
        };
        MarketDetailResponse: {
            /**
             * @description Block the data is as of (SI-R13)
             * @example 1000000000000000000
             */
            asOfBlock: string;
            /**
             * @description ISO 8601 UTC
             * @example 2026-10-01T16:00:00.000Z
             */
            asOfTime: string;
            /** @description asOfBlock ≤ the chain's finalized block (SI-R3) */
            confirmed: boolean;
            /** @description asOfBlock ≤ the chain's safe block */
            safe: boolean;
            scope: string;
            data: components["schemas"]["MarketDetail"];
        };
        MarketDetail: components["schemas"]["Market"] & {
            params: {
                /**
                 * @description Decimal string
                 * @example 1234.56
                 */
                lltv: string;
                /**
                 * @description Decimal string
                 * @example 1234.56
                 */
                uMax: string;
                /**
                 * @description Decimal string
                 * @example 1234.56
                 */
                hfMinOpen: string;
                /**
                 * @description Vault V2 absolute cap, wSTOCK units
                 * @example 1234.56
                 */
                supplyCapShares: string;
                /**
                 * @description Cap at the current feed price
                 * @example 1234.56
                 */
                supplyCapUsd: string;
                perAddressCapUsd: number;
                oracle: {
                    /**
                     * @description Decimal string
                     * @example 1234.56
                     */
                    z: string;
                    /**
                     * @description Decimal string
                     * @example 1234.56
                     */
                    sigma: string;
                    /**
                     * @description Decimal string
                     * @example 1234.56
                     */
                    bMin: string;
                    /**
                     * @description Decimal string
                     * @example 1234.56
                     */
                    bMax: string;
                    rampInSec: number;
                    heartbeatSec: number;
                    staleGraceSec: number;
                };
            };
            schedule: {
                sessionOpen: boolean;
                /**
                 * @description Decimal string
                 * @example 1234.56
                 */
                bufferNow: string;
                /**
                 * @description ISO 8601 UTC
                 * @example 2026-10-01T16:00:00.000Z
                 */
                nextClose: string | null;
                /**
                 * @description ISO 8601 UTC
                 * @example 2026-10-01T16:00:00.000Z
                 */
                rampStart: string | null;
                /**
                 * @description ISO 8601 UTC
                 * @example 2026-10-01T16:00:00.000Z
                 */
                reopen: string | null;
                /**
                 * @description Decimal string
                 * @example 1234.56
                 */
                bufferAtClose: string | null;
                nextEvent: {
                    /**
                     * @description ISO 8601 UTC
                     * @example 2026-10-01T16:00:00.000Z
                     */
                    fullBy: string;
                    /**
                     * @description ISO 8601 UTC
                     * @example 2026-10-01T16:00:00.000Z
                     */
                    release: string;
                    /**
                     * @description Decimal string
                     * @example 1234.56
                     */
                    buffer: string;
                } | null;
            };
            contracts: {
                /** @example 0x0000000000000000000000000000000000000000 */
                stockToken: string;
                /** @example 0x0000000000000000000000000000000000000000 */
                wrapper: string;
                /** @example 0x0000000000000000000000000000000000000000 */
                oracle: string;
                /** @example 0x0000000000000000000000000000000000000000 */
                vault: string;
                /** @example 0x0000000000000000000000000000000000000000 */
                adapter: string;
                /** @example 0x0000000000000000000000000000000000000000 */
                morpho: string;
                /** @example 0x0000000000000000000000000000000000000000 */
                router: string | null;
                /** @example 0x0000000000000000000000000000000000000000 */
                lens: string | null;
                /** @example 0x0000000000000000000000000000000000000000 */
                marketHours: string;
            };
        };
        HistoryResponse: {
            /**
             * @description Block the data is as of (SI-R13)
             * @example 1000000000000000000
             */
            asOfBlock: string;
            /**
             * @description ISO 8601 UTC
             * @example 2026-10-01T16:00:00.000Z
             */
            asOfTime: string;
            /** @description asOfBlock ≤ the chain's finalized block (SI-R3) */
            confirmed: boolean;
            /** @description asOfBlock ≤ the chain's safe block */
            safe: boolean;
            scope: string;
            symbol: string;
            interval: string;
            data: components["schemas"]["HistoryPoint"][];
        };
        HistoryPoint: {
            /**
             * @description ISO 8601 UTC
             * @example 2026-10-01T16:00:00.000Z
             */
            bucket: string;
            /**
             * @description Integer as a decimal string (raw onchain units)
             * @example 1000000000000000000
             */
            blockNumber: string;
            /**
             * @description Decimal string
             * @example 1234.56
             */
            supplied: string;
            /**
             * @description Decimal string
             * @example 1234.56
             */
            borrowed: string;
            /**
             * @description Decimal string
             * @example 1234.56
             */
            borrowedUsd: string;
            /**
             * @description Decimal string
             * @example 1234.56
             */
            utilization: string;
            /**
             * @description Decimal string
             * @example 1234.56
             */
            utilizationVault: string;
            /**
             * @description Decimal string
             * @example 1234.56
             */
            borrowApr: string;
            supplyApy: number;
            /**
             * @description Decimal string
             * @example 1234.56
             */
            siPctFloat: string;
            borrowers: number;
            marketStatus: string;
            /**
             * @description Decimal string
             * @example 1234.56
             */
            buffer: string;
            /**
             * @description Decimal string
             * @example 1234.56
             */
            priceUsdPerShare: string;
            /**
             * @description Decimal string
             * @example 1234.56
             */
            borrowFlow: string;
            /**
             * @description Decimal string
             * @example 1234.56
             */
            repayFlow: string;
            /**
             * @description Decimal string
             * @example 1234.56
             */
            liquidationFlow: string;
        };
        EventsResponse: {
            /**
             * @description Block the data is as of (SI-R13)
             * @example 1000000000000000000
             */
            asOfBlock: string;
            /**
             * @description ISO 8601 UTC
             * @example 2026-10-01T16:00:00.000Z
             */
            asOfTime: string;
            /** @description asOfBlock ≤ the chain's finalized block (SI-R3) */
            confirmed: boolean;
            /** @description asOfBlock ≤ the chain's safe block */
            safe: boolean;
            scope: string;
            data: components["schemas"]["Event"][];
            nextCursor: string | null;
        };
        Event: {
            id: string;
            symbol: string;
            type: string;
            source: string;
            account: string | null;
            /**
             * @description Decimal string
             * @example 1234.56
             */
            assets: string | null;
            /**
             * @description Integer as a decimal string (raw onchain units)
             * @example 1000000000000000000
             */
            shares: string | null;
            data: {
                [key: string]: unknown;
            } | null;
            /**
             * @description Integer as a decimal string (raw onchain units)
             * @example 1000000000000000000
             */
            blockNumber: string;
            logIndex: number;
            /**
             * @description ISO 8601 UTC
             * @example 2026-10-01T16:00:00.000Z
             */
            time: string;
            txHash: string;
        };
        PositionsResponse: {
            /**
             * @description Block the data is as of (SI-R13)
             * @example 1000000000000000000
             */
            asOfBlock: string;
            /**
             * @description ISO 8601 UTC
             * @example 2026-10-01T16:00:00.000Z
             */
            asOfTime: string;
            /** @description asOfBlock ≤ the chain's finalized block (SI-R3) */
            confirmed: boolean;
            /** @description asOfBlock ≤ the chain's safe block */
            safe: boolean;
            scope: string;
            address: string;
            data: components["schemas"]["Position"][];
        };
        Position: {
            symbol: string;
            /** @enum {string} */
            role: "account" | "vault-adapter";
            /**
             * @description Integer as a decimal string (raw onchain units)
             * @example 1000000000000000000
             */
            supplyShares: string;
            /**
             * @description Integer as a decimal string (raw onchain units)
             * @example 1000000000000000000
             */
            borrowShares: string;
            /**
             * @description Decimal string
             * @example 1234.56
             */
            borrowed: string;
            /**
             * @description Decimal string
             * @example 1234.56
             */
            collateralUsdg: string;
            /**
             * @description Decimal string
             * @example 1234.56
             */
            healthFactor: string | null;
            /**
             * @description Decimal string
             * @example 1234.56
             */
            liquidationPriceUsdPerToken: string | null;
            /**
             * @description Integer as a decimal string (raw onchain units)
             * @example 1000000000000000000
             */
            updatedBlock: string;
        };
        StatusResponse: {
            /**
             * @description Block the data is as of (SI-R13)
             * @example 1000000000000000000
             */
            asOfBlock: string;
            /**
             * @description ISO 8601 UTC
             * @example 2026-10-01T16:00:00.000Z
             */
            asOfTime: string;
            /** @description asOfBlock ≤ the chain's finalized block (SI-R3) */
            confirmed: boolean;
            /** @description asOfBlock ≤ the chain's safe block */
            safe: boolean;
            scope: string;
            data: {
                chainId: number;
                network: string;
                indexer: {
                    /**
                     * @description Integer as a decimal string (raw onchain units)
                     * @example 1000000000000000000
                     */
                    headBlock: string;
                    /**
                     * @description ISO 8601 UTC
                     * @example 2026-10-01T16:00:00.000Z
                     */
                    headTime: string;
                    /**
                     * @description Integer as a decimal string (raw onchain units)
                     * @example 1000000000000000000
                     */
                    chainBlock: string | null;
                    lagBlocks: number | null;
                    /**
                     * @description Integer as a decimal string (raw onchain units)
                     * @example 1000000000000000000
                     */
                    safeBlock: string;
                    /**
                     * @description Integer as a decimal string (raw onchain units)
                     * @example 1000000000000000000
                     */
                    finalizedBlock: string;
                };
                markets: {
                    symbol: string;
                    /** @enum {string} */
                    marketStatus: "open" | "closed" | "ramping" | "guard_tripped";
                    /**
                     * @description Integer as a decimal string (raw onchain units)
                     * @example 1000000000000000000
                     */
                    snapshotBlock: string;
                    oracle: {
                        /**
                         * @description Decimal string
                         * @example 1234.56
                         */
                        usdPerToken: string;
                        /**
                         * @description ISO 8601 UTC
                         * @example 2026-10-01T16:00:00.000Z
                         */
                        updatedAt: string;
                        ageSec: number;
                        sessionOpen: boolean;
                        stale: boolean;
                    };
                    guard: {
                        tripped: boolean;
                        reasons: string[];
                        /**
                         * @description Integer as a decimal string (raw onchain units)
                         * @example 1000000000000000000
                         */
                        mask: string;
                    };
                }[];
            };
        };
        RevenueResponse: {
            /**
             * @description Block the data is as of (SI-R13)
             * @example 1000000000000000000
             */
            asOfBlock: string;
            /**
             * @description ISO 8601 UTC
             * @example 2026-10-01T16:00:00.000Z
             */
            asOfTime: string;
            /** @description asOfBlock ≤ the chain's finalized block (SI-R3) */
            confirmed: boolean;
            /** @description asOfBlock ≤ the chain's safe block */
            safe: boolean;
            scope: string;
            /**
             * @description ISO 8601 UTC
             * @example 2026-10-01T16:00:00.000Z
             */
            from: string;
            /**
             * @description ISO 8601 UTC
             * @example 2026-10-01T16:00:00.000Z
             */
            to: string;
            /**
             * @description Historical, variable; not a promise of future revenue (CP-R7)
             * @enum {string}
             */
            rateKind: "variable";
            data: {
                days: {
                    /**
                     * @description UTC day, YYYY-MM-DD
                     * @example 2026-10-01
                     */
                    day: string;
                    symbol: string;
                    /**
                     * @description Borrow interest reaching rSTOCK lenders before the fee, in Stock Token units
                     * @example 1234.56
                     */
                    interest: string;
                    /**
                     * @description Performance fee (interest × fee), in Stock Token units
                     * @example 1234.56
                     */
                    fee: string;
                    /**
                     * @description Fee in USD at the oracle feed price of each accrual block
                     * @example 1234.56
                     */
                    feeUsd: string;
                    accruals: number;
                    raw: {
                        /**
                         * @description Integer as a decimal string (raw onchain units)
                         * @example 1000000000000000000
                         */
                        interestAssets: string;
                        /**
                         * @description Integer as a decimal string (raw onchain units)
                         * @example 1000000000000000000
                         */
                        feeShares: string;
                        /**
                         * @description Integer as a decimal string (raw onchain units)
                         * @example 1000000000000000000
                         */
                        feeAssets: string;
                        /**
                         * @description Integer as a decimal string (raw onchain units)
                         * @example 1000000000000000000
                         */
                        feeUsdWad: string;
                    };
                }[];
                totals: {
                    /**
                     * @description Decimal string
                     * @example 1234.56
                     */
                    feeUsd: string;
                    bySymbol: {
                        symbol: string;
                        /**
                         * @description Decimal string
                         * @example 1234.56
                         */
                        fee: string;
                        /**
                         * @description Decimal string
                         * @example 1234.56
                         */
                        feeUsd: string;
                        raw: {
                            /**
                             * @description Integer as a decimal string (raw onchain units)
                             * @example 1000000000000000000
                             */
                            feeShares: string;
                            /**
                             * @description Integer as a decimal string (raw onchain units)
                             * @example 1000000000000000000
                             */
                            feeAssets: string;
                        };
                    }[];
                };
                /** @description FeeSplitter payouts (FE-R2) */
                distributed: {
                    count: number;
                    /**
                     * @description Decimal string
                     * @example 1234.56
                     */
                    usd: string;
                };
                /** @description FeeConverter sales to USDG (FE-R4) */
                converted: {
                    count: number;
                    /**
                     * @description Decimal string
                     * @example 1234.56
                     */
                    usdg: string;
                    /**
                     * @description Decimal string
                     * @example 1234.56
                     */
                    usd: string;
                };
            };
        };
        VaultOverviewResponse: {
            /**
             * @description Block the data is as of (SI-R13)
             * @example 1000000000000000000
             */
            asOfBlock: string;
            /**
             * @description ISO 8601 UTC
             * @example 2026-10-01T16:00:00.000Z
             */
            asOfTime: string;
            /** @description asOfBlock ≤ the chain's finalized block (SI-R3) */
            confirmed: boolean;
            /** @description asOfBlock ≤ the chain's safe block */
            safe: boolean;
            scope: string;
            data: {
                /**
                 * @description USDG per share at the current NAV
                 * @example 1234.56
                 */
                sharePrice: string;
                /**
                 * @description NAV, USDG
                 * @example 1234.56
                 */
                tvl: string;
                /**
                 * @description Decimal string
                 * @example 1234.56
                 */
                cap: string;
                /**
                 * @description USDG withdrawable without queueing now (0 while the NAV is stale or the market closed)
                 * @example 1234.56
                 */
                instantCapacity: string;
                /** @description Net APY from the share price over the window: historical, variable (CP-R7); null until the window has history */
                apy: {
                    /**
                     * @description Fraction as a decimal string (0.0934 = 9.34%)
                     * @example 0.0934
                     */
                    d7: string | null;
                    /**
                     * @description Fraction as a decimal string (0.0934 = 9.34%)
                     * @example 0.0934
                     */
                    d30: string | null;
                    /**
                     * @description Fraction as a decimal string (0.0934 = 9.34%)
                     * @example 0.0934
                     */
                    d90: string | null;
                };
                /** @description Daily net APY (historical) */
                apySeries: {
                    /** @description UTC seconds (day start) */
                    t: number;
                    /**
                     * @description Decimal string
                     * @example 1234.56
                     */
                    v: string;
                }[];
                sharePriceSeries: {
                    /** @description UTC seconds (day start) */
                    t: number;
                    /**
                     * @description Decimal string
                     * @example 1234.56
                     */
                    v: string;
                }[];
                split: {
                    /** @enum {string} */
                    window: "7d" | "30d" | "90d";
                    /**
                     * @description The rest of the net return: lending income plus the hedge residual
                     * @example 0.0934
                     */
                    lending: string;
                    /**
                     * @description Fraction as a decimal string (0.0934 = 9.34%)
                     * @example 0.0934
                     */
                    funding: string;
                    /**
                     * @description Fraction as a decimal string (0.0934 = 9.34%)
                     * @example 0.0934
                     */
                    buffer: string;
                    /**
                     * @description Trading costs and the performance fee (negative)
                     * @example 0.0934
                     */
                    costs: string;
                }[];
                sleeves: {
                    symbol: string;
                    /**
                     * @description Fraction as a decimal string (0.0934 = 9.34%)
                     * @example 0.0934
                     */
                    weight: string;
                    /**
                     * @description Decimal string
                     * @example 1234.56
                     */
                    cap: string;
                    /**
                     * @description Fraction as a decimal string (0.0934 = 9.34%)
                     * @example 0.0934
                     */
                    delta: string;
                    /**
                     * @description Decimal string
                     * @example 1234.56
                     */
                    marginRatio: string | null;
                    /** @enum {string} */
                    status: "active" | "unwound";
                    /**
                     * @description Decimal string
                     * @example 1234.56
                     */
                    spotUsdg: string;
                    /**
                     * @description Decimal string
                     * @example 1234.56
                     */
                    lentUnits: string;
                    /**
                     * @description Decimal string
                     * @example 1234.56
                     */
                    shortUnits: string;
                }[];
                allocation: {
                    /**
                     * @description Fraction as a decimal string (0.0934 = 9.34%)
                     * @example 0.0934
                     */
                    lent: string;
                    /**
                     * @description Fraction as a decimal string (0.0934 = 9.34%)
                     * @example 0.0934
                     */
                    held: string;
                    /**
                     * @description Fraction as a decimal string (0.0934 = 9.34%)
                     * @example 0.0934
                     */
                    perpMargin: string;
                    /**
                     * @description Fraction as a decimal string (0.0934 = 9.34%)
                     * @example 0.0934
                     */
                    cash: string;
                };
                nav: {
                    ageSec: number | null;
                    stale: boolean;
                    maxAgeClosedSec: number;
                };
                venue: {
                    name: string;
                    /** @enum {string} */
                    status: "ok" | "halted";
                };
                killSwitch: {
                    symbol: string;
                    /**
                     * @description ISO 8601 UTC
                     * @example 2026-10-01T16:00:00.000Z
                     */
                    since: string;
                }[];
                /**
                 * @description ISO 8601 UTC
                 * @example 2026-10-01T16:00:00.000Z
                 */
                lastRebalance: string | null;
                /**
                 * @description Fraction as a decimal string (0.0934 = 9.34%)
                 * @example 0.0934
                 */
                bandPct: string;
                /**
                 * @description Decimal string
                 * @example 1234.56
                 */
                marginTarget: string;
                /**
                 * @description Decimal string
                 * @example 1234.56
                 */
                marginTargetClosed: string;
                marketClosed: boolean;
                depositsOpen: boolean;
                /** @enum {string|null} */
                pauseReason: "cap_zero" | "cap_full" | "nav_stale" | "paused" | null;
                queue: {
                    length: number;
                    /**
                     * @description Decimal string
                     * @example 1234.56
                     */
                    escrowedShares: string;
                };
                contracts: {
                    /** @example 0x0000000000000000000000000000000000000000 */
                    vault: string;
                    /** @example 0x0000000000000000000000000000000000000000 */
                    strategy: string;
                    /** @example 0x0000000000000000000000000000000000000000 */
                    navOracle: string;
                    /** @example 0x0000000000000000000000000000000000000000 */
                    perpAdapter: string;
                };
                /** @enum {string} */
                rateKind: "variable";
            };
        };
        VaultAccountResponse: {
            /**
             * @description Block the data is as of (SI-R13)
             * @example 1000000000000000000
             */
            asOfBlock: string;
            /**
             * @description ISO 8601 UTC
             * @example 2026-10-01T16:00:00.000Z
             */
            asOfTime: string;
            /** @description asOfBlock ≤ the chain's finalized block (SI-R3) */
            confirmed: boolean;
            /** @description asOfBlock ≤ the chain's safe block */
            safe: boolean;
            scope: string;
            data: {
                address: string;
                /**
                 * @description Decimal string
                 * @example 1234.56
                 */
                shares: string;
                /**
                 * @description shares × the current share price, USDG
                 * @example 1234.56
                 */
                value: string;
                /**
                 * @description Deposited minus withdrawn and claimed, USDG
                 * @example 1234.56
                 */
                netDeposits: string;
                requests: {
                    id: string;
                    /** @example 0x0000000000000000000000000000000000000000 */
                    owner: string;
                    /** @example 0x0000000000000000000000000000000000000000 */
                    receiver: string;
                    /**
                     * @description Decimal string
                     * @example 1234.56
                     */
                    shares: string;
                    /**
                     * @description Decimal string
                     * @example 1234.56
                     */
                    assets: string | null;
                    /**
                     * @description ISO 8601 UTC
                     * @example 2026-10-01T16:00:00.000Z
                     */
                    requestedAt: string;
                    /**
                     * @description ISO 8601 UTC
                     * @example 2026-10-01T16:00:00.000Z
                     */
                    settlesAt: string;
                    /** @enum {string} */
                    status: "queued" | "ready" | "claimed";
                    position: number;
                }[];
            };
        };
        ReceiptMarketsResponse: {
            /**
             * @description Block the data is as of (SI-R13)
             * @example 1000000000000000000
             */
            asOfBlock: string;
            /**
             * @description ISO 8601 UTC
             * @example 2026-10-01T16:00:00.000Z
             */
            asOfTime: string;
            /** @description asOfBlock ≤ the chain's finalized block (SI-R3) */
            confirmed: boolean;
            /** @description asOfBlock ≤ the chain's safe block */
            safe: boolean;
            scope: string;
            data: {
                symbol: string;
                marketId: string;
                /** @example 0x0000000000000000000000000000000000000000 */
                usdgVault: string;
                /** @example 0x0000000000000000000000000000000000000000 */
                oracle: string;
                /**
                 * @description Decimal string
                 * @example 1234.56
                 */
                lltv: string;
                /** @description The curator's timelocked listing raised the cap (A3) */
                listed: boolean;
                /**
                 * @description Decimal string
                 * @example 1234.56
                 */
                capUsdg: string;
                /**
                 * @description Decimal string
                 * @example 1234.56
                 */
                supplied: string;
                /**
                 * @description Decimal string
                 * @example 1234.56
                 */
                borrowed: string;
                /**
                 * @description Fraction as a decimal string (0.0934 = 9.34%)
                 * @example 0.0934
                 */
                utilization: string;
                /**
                 * @description rSTOCK posted as collateral
                 * @example 1234.56
                 */
                collateralShares: string;
                /**
                 * @description Decimal string
                 * @example 1234.56
                 */
                stockPriceUsd: string;
                /** @enum {string} */
                rateKind: "variable";
            }[];
        };
        TermsResponse: {
            terms: string;
            attribution: string;
            warranty: string;
        };
        NonceResponse: {
            nonce: string;
            domain: string;
            chainId: number;
            statement: string;
        };
        CreateKeyResponse: {
            id: string;
            /** @description Shown once; store it */
            key: string;
            address: string;
            /** @enum {string} */
            tier: "keyed";
        };
        KeysResponse: {
            address: string;
            keys: {
                id: string;
                label: string | null;
                /**
                 * @description ISO 8601 UTC
                 * @example 2026-10-01T16:00:00.000Z
                 */
                createdAt: string;
                /**
                 * @description ISO 8601 UTC
                 * @example 2026-10-01T16:00:00.000Z
                 */
                revokedAt: string | null;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
